version: "3.12"

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db

  redis:
    image: redis
    ports:
      - 6379
  app:
    build:
      context: .
      target: development
    command: |
      sh entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
